export const platformCopy = {
  accessIdLabel: 'ACCESS ID',
  passphraseLabel: 'PASSPHRASE',
  passphrasePlaceholder: '••••••••',
  forgotLink: 'Forgot Password?',
  submit: 'INITIALIZE SESSION',
  submitBusy: 'AUTHENTICATING...',
  footerLine1: 'RESTRICTED ACCESS. UNAUTHORIZED CONNECTIONS WILL BE TERMINATED.',
  footerLine2: 'Authorized personnel only.',
  loginFailed: 'Login failed',
  logout: 'Terminate Session',
  dashboardSubtitle: 'Real-time label performance metrics',
  kpiMonthlyRevenue: 'MONTHLY REVENUE',
  kpiQuarterlyProjection: 'QUARTERLY PROJECTION',
  kpiAnnualProjection: 'ANNUAL PROJECTION',
  kpiActiveArtists: 'ACTIVE ARTISTS',
  loaderCaption: 'INITIALIZING NEURAL LINK...',
  errorKicker: 'CONNECTION FAILURE',
  errorRetry: 'RETRY CONNECTION',
  errorNetwork: 'Failed to connect to Neural Link',
  errorGeneric: 'ERR',
  accessDenied: 'ACCESS DENIED',
  nav: {
    dashboard: 'Dashboard',
    artists: 'Artists',
    anr: 'A&R Room',
    intelligence: 'Intelligence',
    marketing: 'Marketing',
    fans: 'Fans',
    operations: 'Operations',
    admin: 'Admin',
    settings: 'Settings',
  },
  // Screen-reader-only strings (aria-label). Not part of the architecture §13.1 voice canon;
  // listed here so every rendered string is in one reviewable place (static audit F-08).
  a11y: {
    loading: 'Loading',
    openNavigation: 'Open navigation',
    primaryNav: 'Primary',
    secondaryNav: 'Secondary',
  },
};
