// PLATFORM voice (FRONTEND_ARCHITECTURE.md §13.1). Label-neutral by construction: no label
// name, artist, domain or venue appears here — those are brand DATA on the active profile,
// and a profile may override any key below through `profile.copy`.
export const platformCopy = {
  accessIdLabel: 'ACCESS ID',
  passphraseLabel: 'PASSPHRASE',
  passphrasePlaceholder: '••••••••',
  forgotLink: 'Forgot Password?',
  forgotPrompt: 'Enter your access ID and we will send a reset link.',
  forgotSend: 'SEND RESET LINK',
  forgotBusy: 'SENDING...',
  forgotBack: 'Back to sign in',
  forgotSent: 'If an account exists for that access ID, a reset link has been sent.',
  resetNewLabel: 'NEW PASSPHRASE',
  resetConfirmLabel: 'CONFIRM PASSPHRASE',
  resetSubmit: 'RESET PASSPHRASE',
  resetBusy: 'RESETTING...',
  resetMismatch: 'Passphrases do not match.',
  resetTooShort: 'Passphrase must be at least 8 characters.',
  resetNoToken: 'This reset link is missing its token. Request a new one from the sign-in page.',
  resetDone: 'Passphrase reset. Sign in with the new one.',
  resetToLogin: 'Back to sign in',
  submit: 'INITIALIZE SESSION',
  submitBusy: 'AUTHENTICATING...',
  footerLine1: 'RESTRICTED ACCESS. UNAUTHORIZED CONNECTIONS WILL BE TERMINATED.',
  footerLine2: 'Authorized personnel only.',
  loginFailed: 'Login failed',
  logout: 'Terminate Session',
  dashboardSubtitle: 'Real-time label performance metrics',
  kpiMonthlyRevenue: 'MONTHLY REVENUE',
  kpiQuarterlyProjection: 'QUARTERLY PROJECTION',
  kpiAnnualProjection: 'ANNUAL PROJECTION',
  kpiActiveArtists: 'ACTIVE ARTISTS',
  loaderCaption: 'INITIALIZING NEURAL LINK...',
  errorKicker: 'CONNECTION FAILURE',
  errorRetry: 'RETRY CONNECTION',
  errorNetwork: 'Failed to connect to Neural Link',
  errorGeneric: 'ERR',
  accessDenied: 'ACCESS DENIED',
  accessDeniedDetail: 'This section is not part of your access grant.',
  notFoundTitle: '404',
  notFoundDetail: 'ROUTE NOT FOUND',

  // ---------- shared surface vocabulary ----------
  empty: 'NO DATA',
  emptyDetail: 'Nothing has been recorded for this view yet.',
  loading: 'LOADING',
  confirm: 'CONFIRM',
  cancel: 'CANCEL',
  save: 'SAVE',
  create: 'CREATE',
  update: 'UPDATE',
  remove: 'DELETE',
  close: 'CLOSE',
  retry: 'RETRY',
  search: 'SEARCH',
  refresh: 'REFRESH',
  provenance: 'SOURCE',
  provenanceMock: 'SOURCE: MOCK',
  provenanceFixture: 'SOURCE: FIXTURE',
  provenancePrototype: 'PROTOTYPE',
  provenanceLive: 'SOURCE: LIVE API',

  // ---------- artists ----------
  artistsSearchPlaceholder: 'Filter roster...',
  artistsColName: 'ARTIST',
  artistsColTier: 'TIER',
  artistsColListeners: 'MONTHLY LISTENERS',
  artistsColStreams: 'TOTAL STREAMS',
  artistsColGrowth: 'GROWTH',
  artistsColRevenue: 'REVENUE',
  artistsColActions: '',
  artistsSignTitle: 'SIGN ARTIST',
  artistsSignName: 'NAME',
  artistsSignTier: 'TIER',
  artistsSignSubmit: 'SIGN',
  artistsArchive: 'ARCHIVE',
  artistsRestore: 'RESTORE',
  artistsArchiveConfirm: 'Archive this artist?',
  artistsRestoreConfirm: 'Restore this artist?',
  artistsShowArchived: 'SHOW ARCHIVED',
  artistsView: 'VIEW',
  artistsEmpty: 'NO ARTISTS MATCH',
  artistDetailBack: 'BACK TO ROSTER',
  artistDetailOverview: 'OVERVIEW',
  artistDetailRevenue: 'REVENUE',
  artistDetailTouring: 'TOURING',
  artistDetailSocial: 'SOCIAL',
  artistDetailAudit: 'ENTITY AUDIT',
  artistImageLabel: 'IMAGE OVERRIDE URL',
  artistImageApply: 'APPLY',
  auditRefresh: 'REFRESH AUDIT',
  auditRefreshConfirm: 'CONFIRM PAY',
  auditRefreshWarning: 'A refresh calls paid upstream providers. This is billed per request.',
  auditScore: 'CONFIDENCE',

  // ---------- A&R ----------
  anrWhiteboard: 'WHITEBOARD',
  anrNowListening: 'NOW LISTENING',
  anrDemos: 'DEMO QUEUE',
  anrRate: 'RATE',
  anrTally: 'TALLY',
  anrSubmissions: 'SUBMISSIONS',
  anrSubmitTitle: 'SUBMIT DEMO',
  anrArtist: 'ARTIST',
  anrTrack: 'TRACK',
  anrGenre: 'GENRE',
  anrUrl: 'URL',
  anrSubmit: 'SUBMIT',
  anrVoteUp: 'UP',
  anrVoteDown: 'DOWN',
  anrVotes: 'VOTES',
  anrScoutTitle: 'SCOUT NETWORK',
  anrScoutPlaceholder: 'Search by genre or name...',
  anrShortlist: 'SHORTLIST',
  anrShortlistTitle: 'SHORTLISTED',
  anrShortlistEmpty: 'NOTHING SHORTLISTED YET',
  anrScoutEmpty: 'NO SCOUT RESULTS',
  anrFollowers: 'FOLLOWERS',
  anrPopularity: 'POPULARITY',
  anrTabRoom: 'A&R ROOM',
  anrTabScouting: 'SCOUTING',

  // ---------- intelligence / AI console ----------
  consoleTitle: 'COMMAND CONSOLE',
  consolePlaceholder: 'Ask a question, or run archive / restore / sign <name>...',
  consoleIdle: '// system ready',
  consoleBusy: 'PROCESSING...',
  consoleRun: 'RUN',
  consoleError: 'ERR // AI query failed',
  consoleSystemDefault: 'SYSTEM DEFAULT',
  consoleReady: 'READY',
  // Console protocol transcripts, ported from the legacy `handleAI` command parser. Platform
  // voice, so they live here rather than in a component or a profile.
  consoleArchiveOk: (name) => `> EXECUTING PROTOCOL: ARCHIVE\n> TARGET: ${name}\n> STATUS: COMPLETED.\n> Entity moved to restricted vault.`,
  consoleRestoreOk: (name) => `> EXECUTING PROTOCOL: RESTORE\n> TARGET: ${name}\n> STATUS: ACTIVE.\n> Entity reintegrated into the Neural Network.`,
  consoleSignOk: (name) => `> NEW ENTITY DETECTED.\n> SIGNING PROTOCOL INITIATED.\n> WELCOME: ${name}\n> TIER: Developing\n> Smart Contract: GENERATED.`,
  consoleTargetMissing: (name) => `TARGET ACQUISITION FAILED: '${name}' not found in roster database.`,
  consoleCommandFailed: (name, reason) => `CRITICAL FAILURE: ${name} — ${reason}`,
  networkGraphTitle: 'ROSTER NETWORK',
  networkTierCore: 'CORE',
  networkTierDeveloping: 'DEVELOPING',
  networkTierArchived: 'ARCHIVED',

  // ---------- marketing ----------
  marketingStats: 'CRM REACH',
  marketingEmails: 'TOTAL EMAILS',
  marketingSms: 'TOTAL SMS',
  marketingPresale: 'PRESALE SIGNUPS',
  marketingHistory: 'CHANNEL HISTORY',
  marketingWizard: 'CAMPAIGN BUILDER',
  marketingStep: 'STEP',
  marketingName: 'CAMPAIGN NAME',
  marketingChannel: 'CHANNEL',
  marketingAudience: 'AUDIENCE',
  marketingReview: 'REVIEW',
  marketingLaunch: 'GENERATE PLAN',
  marketingNext: 'NEXT',
  marketingBack: 'BACK',
  marketingPlan: 'GENERATED PLAN',

  // ---------- fans ----------
  fansTopMovers: 'TOP MOVERS',
  fansAge: 'AGE DISTRIBUTION',
  fansGender: 'GENDER SPLIT',
  fansLocations: 'TOP CITIES',
  fansGrowth: 'GROWTH',
  fansEngagement: 'ENGAGEMENT',
  fansPlatformGrowth: 'PLATFORM GROWTH',

  // ---------- operations ----------
  opsLogistics: 'LOGISTICS',
  opsAssets: 'ASSET VAULT',
  opsContracts: 'CONTRACTS',
  opsItem: 'ITEM',
  opsQuantity: 'QTY',
  opsStatus: 'STATUS',
  opsVendor: 'VENDOR',
  opsEta: 'ETA',
  opsLocation: 'LOCATION',
  opsTitle: 'TITLE',
  opsType: 'TYPE',
  opsArtist: 'ARTIST',
  opsUploaded: 'UPLOADED',
  opsSize: 'SIZE',
  opsTerm: 'TERM',
  opsAdvance: 'ADVANCE',
  opsRoyalty: 'ROYALTY',
  opsMilestone: 'NEXT MILESTONE',
  opsSigned: 'SIGNED',

  // ---------- settings ----------
  settingsIntegrations: 'INTEGRATIONS',
  settingsAi: 'AI',
  integrationsConnect: 'CONNECT',
  integrationsDisconnect: 'DISCONNECT',
  integrationsConnected: 'CONNECTED',
  integrationsDisconnected: 'NOT CONNECTED',
  integrationsQuota: 'QUOTA',
  integrationsLastSync: 'LAST SYNC',
  integrationsServerManaged: '// credentials are server-managed — no key is entered or stored in this application',
  aiProviderLabel: 'AI PROVIDER',
  aiModelLabel: 'MODEL',
  aiDefaultsLabel: 'DEFAULTS',
  aiStatusLabel: 'PROVIDER STATUS',
  aiByokLabel: 'BRING YOUR OWN KEY',
  aiByokUnavailable: '// not available — credentials are server-managed',
  aiCatalogUnavailable: '// provider catalog unavailable — using system default',

  // ---------- admin ----------
  adminTeam: 'TEAM',
  adminColName: 'NAME',
  adminColEmail: 'EMAIL',
  adminColRole: 'ROLE',
  adminColAccess: 'PAGE ACCESS',
  adminCreateTitle: 'CREATE USER',
  adminEditTitle: 'EDIT USER',
  adminName: 'NAME',
  adminEmail: 'EMAIL',
  adminPassword: 'PASSWORD',
  adminPasswordKeep: 'PASSWORD (blank = unchanged)',
  adminRole: 'ROLE',
  adminArtistAccess: 'ARTIST ACCESS',
  adminPermissions: 'PAGE ACCESS',
  adminEdit: 'EDIT',
  adminDeleteConfirm: 'Delete this user?',
  adminSelfDelete: 'You cannot delete your own account.',
  adminPermissionsNote: 'Page access controls navigation visibility only. The server authorizes every request independently.',

  // ---------- exports ----------
  exportTitle: 'EXPORT',
  exportPdf: 'PDF',
  exportCsv: 'CSV',
  exportBusy: 'GENERATING...',
  exportNote: 'Reports are generated server-side and may take a moment.',
  exportFailed: 'Export failed',

  // ---------- dashboard widgets ----------
  geoTitle: 'GLOBAL HEATMAP',
  geoSource: 'SOURCE: STREAMING DATA',
  geoUnmapped: 'UNMAPPED LOCATIONS',
  forecastTitle: 'REVENUE FORECAST',
  forecastHistorical: 'Historical',
  forecastProjection: 'Projection',
  salesLogTitle: 'LOG SALE',
  salesAmount: 'AMOUNT',
  salesMonth: 'MONTH',
  salesArtist: 'ARTIST',
  salesSubmit: 'RECORD',

  nav: {
    dashboard: 'Dashboard',
    artists: 'Artists',
    anr: 'A&R Room',
    intelligence: 'Intelligence',
    marketing: 'Marketing',
    fans: 'Fans',
    operations: 'Operations',
    admin: 'Admin',
    settings: 'Settings',
  },
  // Screen-reader-only strings (aria-label). Not part of the architecture §13.1 voice canon;
  // listed here so every rendered string is in one reviewable place (static audit F-08).
  a11y: {
    loading: 'Loading',
    openNavigation: 'Open navigation',
    primaryNav: 'Primary',
    secondaryNav: 'Secondary',
    sortBy: 'Sort by',
    map: 'Geographic distribution of streaming activity',
    chart: 'Revenue history and projection',
    network: 'Roster relationship graph',
  },
};
